sonar.projectKey=comicbook-store
sonar.projectName=comicbook-store
sonar.projectVersion=0.0

sonar.sources=\
    apps/

sonar.tests=\
    apps/

sonar.test.inclusions=\
    **/*.spec.ts

sonar.exclusions=\
    **/jest.config.ts,\
    **/*-e2e/**
