sonar.projectKey=comicbook-store
sonar.projectName=comicbook-store
sonar.projectVersion=0.0

sonar.sources=\
    apps/,\
    libs/

sonar.tests=\
    apps/,
    libs/

sonar.test.inclusions=\
    **/*.spec.ts

sonar.ts.eslint.configPath=eslint.config.cjs

sonar.typescript.lcov.reportPaths=\
    coverage/apps/gui/client/lcov.info,\
    coverage/libs/logger/lcov.info

sonar.coverage.exclusions=\
    **/*.type.ts,\
    **/*.model.ts,\
    apps/gui/client/src/main.ts,\
    apps/gui/client/testing/**,\
    apps/gui/client/src/app/infrastructure/api/http-client/in-memory-web-api/*
sonar.exclusions=\
    **/jest.config.ts,\
    **/*-e2e/**,\
    **/jest.test-setup.ts,\
    **/jest.global-setup.ts,\
    **/eslint.config.cjs
