sonar.projectKey=comicbook-store
sonar.projectName=comicbook-store
sonar.projectVersion=0.0

sonar.sources=\
    apps/

sonar.tests=\
    apps/

sonar.test.inclusions=\
    **/*.spec.ts

sonar.ts.eslint.configPath=.eslintrc.json

sonar.typescript.lcov.reportPaths=\
    coverage/apps/gui/lcov.info

sonar.coverage.exclusions=\
    apps/gui/src/main.ts,\
    apps/gui/src/app/infrastructure/ui/app.config.ts,\
    apps/gui/src/app/infrastructure/ui/app.routes.ts,\
    apps/gui/test/**

sonar.exclusions=\
    **/jest.config.ts,\
    **/*-e2e/**,\
    **/test-setup.ts
